---

extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation: disable
  empty-lines:
    max: 3
    level: error
  hyphens:
    max-spaces-after: 1
    level: error
  indentation:
    spaces: 2
    indent-sequences: true
  line-length: disable
  new-lines:
    type: unix
    level: error
  truthy:
    allowed-values:
      - "true"
      - "false"
    level: warning

ignore: |
  .virtualenv
  .cache
