---
- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - include_tasks: "../resources/setup_{{ ansible_os_family | lower }}.yml"

  roles:
    - role: lean_delivery.java
      vars:
        java_distribution: adoptopenjdk
        java_major_version: 8
        java_minor_version: 252
        adoptopenjdk_impl: openj9
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: test_springboot
        steamengine_project_type: springboot
        steamengine_build_url: https://delivery.steamulo.org/SteamEngineV2_tests/hello-world-app-spring-boot.jar
        steamengine_build_checksum: sha1:332ea24fea20f0cecbc2b855b9174c49bd3feff2
        steamengine_project_configuration:
          server:
            port: 8085
