---

- name: Create systemd unit file
  ansible.builtin.template:
    src: systemd_tomcat.service.j2
    dest: "/etc/systemd/system/{{ steamengine_project_name }}.service"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_runtime_tomcat

- name: "Add nginx user in {{ steamengine_app_user }} group"
  ansible.builtin.user:
    name: "{{ (ansible_os_family == 'RedHat') | ternary('nginx', 'www-data') }}"
    groups: "{{ steamengine_app_user }}"
    append: true
  tags:
    - steamengine_runtime_tomcat

- name: "Ensure {{ steamengine_project_name }} is running and set to start on boot"
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    name: "{{ steamengine_project_name }}"
  tags:
    - steamengine_runtime_tomcat
