FROM ubuntu:20.04

ENV container=docker \
    LANGUAGE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    TERM=xterm \
    DEBIAN_FRONTEND="noninteractive"

RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -print0 | xargs -0 rm -vf

RUN apt-get update && \
    INSTALL_PKGS="rsyslog software-properties-common python3 python3-pip python3-setuptools curl sudo bash ca-certificates iproute2 python3-apt aptitude apt-utils locales dbus gnupg systemd systemd-cron" && \
    apt-get install -y $INSTALL_PKGS && \
    localedef -f UTF-8 -i en_US en_US.UTF-8

RUN cp /bin/true /sbin/agetty

STOPSIGNAL SIGRTMIN+3

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT ["/sbin/init"]
